In [6]:
from sklearn.linear_model import SGDClassifier
X=[[0.,0.],[1.,1.]]
y=[0,1]
clf=SGDClassifier(loss='hinge',max_iter=5)
clf.fit(X,y)

/home/pandit/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge', max_iter=5,
              n_iter_no_change=5, n_jobs=None, penalty='l2', power_t=0.5,
              random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [7]:
clf.predict([[2.,2.]])

array([1])

In [8]:
clf.coef_

array([[9.91080278, 9.91080278]])

In [10]:
clf.intercept_

array([-9.97004991])

In [11]:
clf.decision_function([[2.,2.]])

array([29.67316119])

In [12]:
clf=SGDClassifier(loss='log',max_iter=5).fit(X,y)

/home/pandit/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


In [13]:
clf.predict_proba([[1.,1.]])

array([[4.97248476e-07, 9.99999503e-01]])

#### NearestNeighbors

In [14]:
from sklearn.neighbors import NearestNeighbors
import numpy as np

In [15]:
X=np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])
nbrs=NearestNeighbors(n_neighbors=2,algorithm='ball_tree').fit(X)
distances,indices=nbrs.kneighbors(X)

In [16]:
indices

array([[0, 1],
       [1, 0],
       [2, 1],
       [3, 4],
       [4, 3],
       [5, 4]])

In [17]:
distances

array([[0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.41421356],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.41421356]])

In [18]:
nbrs.kneighbors_graph(X).toarray()

array([[1., 1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 1., 1.]])

In [19]:
from sklearn.neighbors import KDTree
import numpy as np
X=np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])
kdt=KDTree(X,leaf_size=30,metric='euclidean')
kdt.query(X,k=2,return_distance=False)

array([[0, 1],
       [1, 0],
       [2, 1],
       [3, 4],
       [4, 3],
       [5, 4]])

#### Nearest Neighbors Classifications

In [22]:
from sklearn.neighbors import (NeighborhoodComponentsAnalysis,KNeighborsClassifier)
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

In [23]:
X,y=load_iris(return_X_y=True)
X_train,X_test,y_train,y_test=train_test_split(X,y,stratify=y,test_size=0.7,random_state=42)

In [25]:
nca=NeighborhoodComponentsAnalysis(random_state=42)
knn=KNeighborsClassifier(n_neighbors=3)
nca_pipe=Pipeline([('nca',nca),('knn',knn)])
nca_pipe.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('nca',
                 NeighborhoodComponentsAnalysis(callback=None, init='auto',
                                                max_iter=50, n_components=None,
                                                random_state=42, tol=1e-05,
                                                verbose=0, warm_start=False)),
                ('knn',
                 KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                      metric='minkowski', metric_params=None,
                                      n_jobs=None, n_neighbors=3, p=2,
                                      weights='uniform'))],
         verbose=False)

In [26]:
print(nca_pipe.score(X_test,y_test))

0.9619047619047619
