# Project HR

Predict attrition of your valuable employees

[IBM HR Analytics Employee Attrition & Performance](https://www.kaggle.com/pavansubhasht/ibm-hr-analytics-attrition-dataset)

In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv(r"G:\DataScience_June2019\CourseMaterials\EnsembleMethods\WA_Fn-UseC_-HR-Employee-Attrition.csv")
df.head(2)

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   

           ...           RelationshipSatisfaction StandardHours  \
0          ...                                  1            80   
1          ...                                  4            80   

   StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                  8                      0               1   
1                 1                 10                      3               3   

   YearsAtCompany YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                  4                        0   
1              10                  7                        1   

   YearsWithCurrManager  
0                     5  
1                     7  

[2 rows x 35 columns]

In [4]:
df.shape

(1470, 35)

In [5]:
#Cleaning of Data - Columns - 'EmployeeNumber', 'Over18', 'StandardHours' and 'EmployeeCount' 
df.drop('EmployeeNumber', axis=1, inplace=True)
df.drop('Over18', axis=1, inplace=True)
df.drop('StandardHours', axis=1, inplace=True)
df.drop('EmployeeCount', axis=1, inplace=True)

In [6]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [7]:
df.shape

(1470, 31)

In [8]:
df.head(2)

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   

   DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                 1          2  Life Sciences                        2   
1                 8          1  Life Sciences                        3   

   Gender         ...           PerformanceRating  RelationshipSatisfaction  \
0  Female         ...                           3                         1   
1    Male         ...                           4                         4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   

  YearsWithCurrManager  
0                    5  
1                    7  

[2 rows x 31 columns]

In [9]:
y = df['Attrition']
X = df.drop('Attrition',axis=1)

In [10]:
y.unique()

array(['Yes', 'No'], dtype=object)

In [11]:
y = pd.get_dummies(y, drop_first=True)
y.shape

(1470, 1)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 31 columns):
Age                         1470 non-null int64
Attrition                   1470 non-null object
BusinessTravel              1470 non-null object
DailyRate                   1470 non-null int64
Department                  1470 non-null object
DistanceFromHome            1470 non-null int64
Education                   1470 non-null int64
EducationField              1470 non-null object
EnvironmentSatisfaction     1470 non-null int64
Gender                      1470 non-null object
HourlyRate                  1470 non-null int64
JobInvolvement              1470 non-null int64
JobLevel                    1470 non-null int64
JobRole                     1470 non-null object
JobSatisfaction             1470 non-null int64
MaritalStatus               1470 non-null object
MonthlyIncome               1470 non-null int64
MonthlyRate                 1470 non-null int64
NumCompaniesWorked    

In [13]:
df.select_dtypes(['object'])

Attrition     BusinessTravel              Department    EducationField  \
0          Yes      Travel_Rarely                   Sales     Life Sciences   
1           No  Travel_Frequently  Research & Development     Life Sciences   
2          Yes      Travel_Rarely  Research & Development             Other   
3           No  Travel_Frequently  Research & Development     Life Sciences   
4           No      Travel_Rarely  Research & Development           Medical   
5           No  Travel_Frequently  Research & Development     Life Sciences   
6           No      Travel_Rarely  Research & Development           Medical   
7           No      Travel_Rarely  Research & Development     Life Sciences   
8           No  Travel_Frequently  Research & Development     Life Sciences   
9           No      Travel_Rarely  Research & Development           Medical   
10          No      Travel_Rarely  Research & Development           Medical   
11          No      Travel_Rarely  Research & Development     Life Sciences   
12          No      Travel_Rarely  Research & Development     Life Sciences   
13          No      Travel_Rarely  Research & Development           Medical   
14         Yes      Travel_Rarely  Research & Development     Life Sciences   
15          No      Travel_Rarely  Research & Development     Life Sciences   
16          No      Travel_Rarely  Research & Development     Life Sciences   
17          No         Non-Travel  Research & Development           Medical   
18          No      Travel_Rarely                   Sales     Life Sciences   
19          No      Travel_Rarely  Research & Development     Life Sciences   
20          No         Non-Travel  Research & Development             Other   
21         Yes      Travel_Rarely                   Sales     Life Sciences   
22          No      Travel_Rarely  Research & Development     Life Sciences   
23          No      Travel_Rarely  Research & Development     Life Sciences   
24         Yes      Travel_Rarely  Research & Development           Medical   
25          No      Travel_Rarely  Research & Development             Other   
26         Yes  Travel_Frequently  Research & Development     Life Sciences   
27          No      Travel_Rarely                   Sales         Marketing   
28          No      Travel_Rarely  Research & Development           Medical   
29          No      Travel_Rarely                   Sales         Marketing   
...        ...                ...                     ...               ...   
1440        No  Travel_Frequently  Research & Development     Life Sciences   
1441        No         Non-Travel  Research & Development     Life Sciences   
1442       Yes      Travel_Rarely  Research & Development           Medical   
1443        No      Travel_Rarely  Research & Development     Life Sciences   
1444       Yes      Travel_Rarely  Research & Development  Technical Degree   
1445        No      Travel_Rarely  Research & Development     Life Sciences   
1446        No      Travel_Rarely                   Sales         Marketing   
1447        No         Non-Travel                   Sales         Marketing   
1448        No      Travel_Rarely                   Sales     Life Sciences   
1449        No      Travel_Rarely  Research & Development  Technical Degree   
1450        No      Travel_Rarely         Human Resources     Life Sciences   
1451        No      Travel_Rarely                   Sales     Life Sciences   
1452       Yes  Travel_Frequently                   Sales     Life Sciences   
1453        No      Travel_Rarely                   Sales         Marketing   
1454        No      Travel_Rarely                   Sales     Life Sciences   
1455        No      Travel_Rarely  Research & Development     Life Sciences   
1456        No  Travel_Frequently  Research & Development     Life Sciences   
1457        No      Travel_Rarely  Research & Development           Medical   
1458        No      Travel_Rarely  Research & Developme

In [14]:
ind_BusinessTravel = pd.get_dummies(df['BusinessTravel'], prefix='BusinessTravel', drop_first=True)
ind_Department = pd.get_dummies(df['Department'], prefix='Department', drop_first=True)
ind_EducationField = pd.get_dummies(df['EducationField'], prefix='EducationField', drop_first=True)
ind_Gender = pd.get_dummies(df['Gender'], prefix='Gender',drop_first=True)
ind_JobRole = pd.get_dummies(df['JobRole'], prefix='JobRole',drop_first=True)
ind_MaritalStatus = pd.get_dummies(df['MaritalStatus'], prefix='MaritalStatus',drop_first=True)
ind_OverTime = pd.get_dummies(df['OverTime'], prefix='OverTime',drop_first=True)

In [15]:
ind_BusinessTravel.head()

BusinessTravel_Travel_Frequently  BusinessTravel_Travel_Rarely
0                                 0                             1
1                                 1                             0
2                                 0                             1
3                                 1                             0
4                                 0                             1

In [16]:
df['BusinessTravel'].unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'], dtype=object)

In [17]:
df.select_dtypes(['int64']).head(2)

Age  DailyRate  DistanceFromHome  Education  EnvironmentSatisfaction  \
0   41       1102                 1          2                        2   
1   49        279                 8          1                        3   

   HourlyRate  JobInvolvement  JobLevel  JobSatisfaction  MonthlyIncome  \
0          94               3         2                4           5993   
1          61               2         2                2           5130   

           ...           PerformanceRating  RelationshipSatisfaction  \
0          ...                           3                         1   
1          ...                           4                         4   

   StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                 0                  8                      0   
1                 1                 10                      3   

   WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                1               6                   4   
1                3              10                   7   

   YearsSinceLastPromotion  YearsWithCurrManager  
0                        0                     5  
1                        1                     7  

[2 rows x 23 columns]

In [18]:
df1 = pd.concat([ind_BusinessTravel, ind_Department, ind_EducationField, ind_Gender, 
                 ind_JobRole, ind_MaritalStatus, ind_OverTime, df.select_dtypes(['int64'])], axis=1)

In [19]:
df1.shape

(1470, 44)

# Decision Tree

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df1, y, test_size=0.3, random_state=42)

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
clf = DecisionTreeClassifier(random_state=42)

In [23]:
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=42,
            splitter='best')

In [24]:
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [25]:
def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    '''
    print the accuracy score, classification report and confusion matrix of classifier
    '''
    if train:
        '''
        training performance
        '''
        print("Train Result:\n")
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_train, clf.predict(X_train))))
        print("Classification Report: \n {}\n".format(classification_report(y_train, clf.predict(X_train))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_train, clf.predict(X_train))))

        res = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))
        
    elif train==False:
        '''
        test performance
        '''
        print("Test Result:\n")        
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, clf.predict(X_test))))
        print("Classification Report: \n {}\n".format(classification_report(y_test, clf.predict(X_test))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, clf.predict(X_test))))    
        

In [26]:
print_score(clf, X_train, y_train, X_test, y_test, train=True)

Train Result:

accuracy score: 1.0000

Classification Report: 
              precision    recall  f1-score   support

          0       1.00      1.00      1.00       853
          1       1.00      1.00      1.00       176

avg / total       1.00      1.00      1.00      1029


Confusion Matrix: 
 [[853   0]
 [  0 176]]

Average Accuracy: 	 0.7716
Accuracy SD: 		 0.0244


In [27]:
print_score(clf, X_train, y_train, X_test, y_test, train=False)

Test Result:

accuracy score: 0.7755

Classification Report: 
              precision    recall  f1-score   support

          0       0.90      0.84      0.87       380
          1       0.28      0.39      0.33        61

avg / total       0.81      0.78      0.79       441


Confusion Matrix: 
 [[318  62]
 [ 37  24]]



# Bagging

In [28]:
from sklearn.ensemble import BaggingClassifier

In [29]:
bag_clf = BaggingClassifier(base_estimator=clf, n_estimators=5000,
                            bootstrap=True, n_jobs=-1, random_state=42)

In [30]:
bag_clf.fit(X_train, y_train)

F:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=42,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=5000, n_jobs=-1, oob_score=False,
         random_state=42, verbose=0, warm_start=False)

In [31]:
print_score(bag_clf, X_train, y_train, X_test, y_test, train=True)
print_score(bag_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:

accuracy score: 1.0000

Classification Report: 
              precision    recall  f1-score   support

          0       1.00      1.00      1.00       853
          1       1.00      1.00      1.00       176

avg / total       1.00      1.00      1.00      1029


Confusion Matrix: 
 [[853   0]
 [  0 176]]



F:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
F:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
F:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
F:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y,

Average Accuracy: 	 0.8561
Accuracy SD: 		 0.0263
Test Result:

accuracy score: 0.8707

Classification Report: 
              precision    recall  f1-score   support

          0       0.88      0.99      0.93       380
          1       0.64      0.15      0.24        61

avg / total       0.85      0.87      0.83       441


Confusion Matrix: 
 [[375   5]
 [ 52   9]]



# Random Forest

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
rf_clf = RandomForestClassifier()

In [34]:
rf_clf.fit(X_train, y_train.values.ravel())

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [35]:
print_score(rf_clf, X_train, y_train.values.ravel(), X_test, y_test.values.ravel(), train=True)
print_score(rf_clf, X_train, y_train.values.ravel(), X_test, y_test.values.ravel(), train=False)

Train Result:

accuracy score: 0.9893

Classification Report: 
              precision    recall  f1-score   support

          0       0.99      1.00      0.99       853
          1       1.00      0.94      0.97       176

avg / total       0.99      0.99      0.99      1029


Confusion Matrix: 
 [[853   0]
 [ 11 165]]

Average Accuracy: 	 0.8407
Accuracy SD: 		 0.0189
Test Result:

accuracy score: 0.8639

Classification Report: 
              precision    recall  f1-score   support

          0       0.88      0.98      0.93       380
          1       0.53      0.15      0.23        61

avg / total       0.83      0.86      0.83       441


Confusion Matrix: 
 [[372   8]
 [ 52   9]]



# AdaBoost

In [36]:
from sklearn.ensemble import AdaBoostClassifier

In [37]:
ada_clf = AdaBoostClassifier()

In [38]:
ada_clf.fit(X_train, y_train.values.ravel())

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [39]:
print_score(ada_clf, X_train, y_train.values.ravel(), X_test, y_test.values.ravel(), train=True)
print_score(ada_clf, X_train, y_train.values.ravel(), X_test, y_test.values.ravel(), train=False)

Train Result:

accuracy score: 0.9067

Classification Report: 
              precision    recall  f1-score   support

          0       0.91      0.98      0.95       853
          1       0.84      0.56      0.67       176

avg / total       0.90      0.91      0.90      1029


Confusion Matrix: 
 [[835  18]
 [ 78  98]]

Average Accuracy: 	 0.8659
Accuracy SD: 		 0.0197
Test Result:

accuracy score: 0.8685

Classification Report: 
              precision    recall  f1-score   support

          0       0.90      0.95      0.93       380
          1       0.54      0.34      0.42        61

avg / total       0.85      0.87      0.86       441


Confusion Matrix: 
 [[362  18]
 [ 40  21]]



# AdaBoost + RandomForest

In [40]:
ada_clf = AdaBoostClassifier(RandomForestClassifier())
ada_clf.fit(X_train, y_train.values.ravel())

AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
          learning_rate=1.0, n_estimators=50, random_state=None)

In [41]:
print_score(ada_clf, X_train, y_train.values.ravel(), X_test, y_test.values.ravel(), train=True)
print_score(ada_clf, X_train, y_train.values.ravel(), X_test, y_test.values.ravel(), train=False)

Train Result:

accuracy score: 1.0000

Classification Report: 
              precision    recall  f1-score   support

          0       1.00      1.00      1.00       853
          1       1.00      1.00      1.00       176

avg / total       1.00      1.00      1.00      1029


Confusion Matrix: 
 [[853   0]
 [  0 176]]

Average Accuracy: 	 0.8387
Accuracy SD: 		 0.0117
Test Result:

accuracy score: 0.8571

Classification Report: 
              precision    recall  f1-score   support

          0       0.87      0.98      0.92       380
          1       0.43      0.10      0.16        61

avg / total       0.81      0.86      0.82       441


Confusion Matrix: 
 [[372   8]
 [ 55   6]]



# Gradient Boosting Classifier

In [42]:
from sklearn.ensemble import GradientBoostingClassifier

In [43]:
gbc_clf = GradientBoostingClassifier()
gbc_clf.fit(X_train, y_train.values.ravel())

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [44]:
print_score(gbc_clf, X_train, y_train.values.ravel(), X_test, y_test.values.ravel(), train=True)
print_score(gbc_clf, X_train, y_train.values.ravel(), X_test, y_test.values.ravel(), train=False)

Train Result:

accuracy score: 0.9543

Classification Report: 
              precision    recall  f1-score   support

          0       0.95      1.00      0.97       853
          1       0.99      0.74      0.85       176

avg / total       0.96      0.95      0.95      1029


Confusion Matrix: 
 [[852   1]
 [ 46 130]]

Average Accuracy: 	 0.8639
Accuracy SD: 		 0.0138
Test Result:

accuracy score: 0.8730

Classification Report: 
              precision    recall  f1-score   support

          0       0.89      0.97      0.93       380
          1       0.59      0.28      0.38        61

avg / total       0.85      0.87      0.85       441


Confusion Matrix: 
 [[368  12]
 [ 44  17]]



# XGBoost

In [45]:
import xgboost as xgb

In [46]:
xgb_clf = xgb.XGBClassifier()
xgb_clf.fit(X_train, y_train.values.ravel())

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [47]:
print_score(xgb_clf, X_train, y_train.values.ravel(), X_test, y_test.values.ravel(), train=True)
print_score(xgb_clf, X_train, y_train.values.ravel(), X_test, y_test.values.ravel(), train=False)

Train Result:



F:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
F:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
F:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


accuracy score: 0.9524

Classification Report: 
              precision    recall  f1-score   support

          0       0.95      1.00      0.97       853
          1       0.98      0.74      0.84       176

avg / total       0.95      0.95      0.95      1029


Confusion Matrix: 
 [[850   3]
 [ 46 130]]



F:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
F:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
F:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
F:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `arra

Average Accuracy: 	 0.8601
Accuracy SD: 		 0.0184
Test Result:

accuracy score: 0.8730

Classification Report: 
              precision    recall  f1-score   support

          0       0.89      0.97      0.93       380
          1       0.60      0.25      0.35        61

avg / total       0.85      0.87      0.85       441


Confusion Matrix: 
 [[370  10]
 [ 46  15]]



F:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
F:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
F:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
F:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `arra